sudo: false
cache: bundler
language: ruby
rvm:
- 2.4.1
before_install: gem install bundler
script: bundle exec rake
notifications:
  email: false
after_success:
- bundle exec codeclimate-test-reporter
env:
  global:
    secure: bc61o3zBXjxDrvLoVGnszyysb4uWLo3JJWjUpPev/wFQ90EOD6suJeQD44BFHLedi786yMILXff3ePF687k6CmyCJm5AEWY6a8YEwa4PGPqHZW51Zl2oB9Xkgev68LUmxGU7DR2KLRTyaBxGdGztctIQtrehHzWprLTQUB6MVd8Vpd8INFSevb84gXvICQmXbRGiFEizMmxV+gNxVmWAJJs+A4S13/r50boHE9sVqERNfjbEFkONfFO4O9kiq3Gv1D+/F+259Zf0h/I/xcPYhWvxJUwfFSrx8PTGUpRrOleyuCMw7jSIVq4xG1bXsppx6LaN0BWaWv7qZ3IB1XHQ5uMvbf/rlxSZyZmuiKpO97jxlJEoMa7d8UaYepslAFgEP90qpkkUSn7O12o/az0Uw3pnY0iL7CgKEn2BCl7j6dBeK6MvariDy7uYcvlIPeILl0HHb9nTtyGd0yrXzWoQli7y2BuB4AhYcwXtJo15OITCnWWy74b3bAm21ozgGzte7k6xZ6EJvFtHcOmc6ah336fnCdb9ZOpDkZqD5yCQyv3uASq6mv2xa+up6DNoUsR3/Mwvdp2e2Rt92QjmQPBWcbSnTotYRfawo5/JoQQZIfUb8dp0zJeGw/06tCFUJpOTCyuDxARJB42RlK610SDsl284/jcU0oPtGvda4cT5OOQ=
